/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArgentaVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCollateral"
      | "borrow"
      | "closeVault"
      | "collateralBalance"
      | "collateralRegistry"
      | "debtEngine"
      | "getHealthFactor"
      | "getPosition"
      | "interestRateModel"
      | "nextVaultId"
      | "openVault"
      | "oracle"
      | "owner"
      | "removeCollateral"
      | "renounceOwnership"
      | "repay"
      | "safetyGuard"
      | "transferOwnership"
      | "vaults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Borrowed"
      | "CollateralAdded"
      | "CollateralRemoved"
      | "OwnershipTransferred"
      | "Repaid"
      | "VaultClosed"
      | "VaultOpened"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCollateral",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "debtEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "interestRateModel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextVaultId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "openVault", values?: undefined): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeCollateral",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safetyGuard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debtEngine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestRateModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextVaultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safetyGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export namespace BorrowedEvent {
  export type InputTuple = [vaultId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [vaultId: bigint, amount: bigint];
  export interface OutputObject {
    vaultId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralAddedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: bigint,
    token: string,
    amount: bigint,
    value: bigint
  ];
  export interface OutputObject {
    vaultId: bigint;
    token: string;
    amount: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralRemovedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: bigint,
    token: string,
    amount: bigint,
    value: bigint
  ];
  export interface OutputObject {
    vaultId: bigint;
    token: string;
    amount: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaidEvent {
  export type InputTuple = [vaultId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [vaultId: bigint, amount: bigint];
  export interface OutputObject {
    vaultId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultClosedEvent {
  export type InputTuple = [vaultId: BigNumberish];
  export type OutputTuple = [vaultId: bigint];
  export interface OutputObject {
    vaultId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultOpenedEvent {
  export type InputTuple = [vaultId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [vaultId: bigint, owner: string];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArgentaVault extends BaseContract {
  connect(runner?: ContractRunner | null): ArgentaVault;
  waitForDeployment(): Promise<this>;

  interface: ArgentaVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCollateral: TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  borrow: TypedContractMethod<
    [vaultId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeVault: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  collateralBalance: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  collateralRegistry: TypedContractMethod<[], [string], "view">;

  debtEngine: TypedContractMethod<[], [string], "view">;

  getHealthFactor: TypedContractMethod<
    [vaultId: BigNumberish],
    [bigint],
    "view"
  >;

  getPosition: TypedContractMethod<
    [vaultId: BigNumberish],
    [[bigint, bigint] & { collateralValue: bigint; debt: bigint }],
    "view"
  >;

  interestRateModel: TypedContractMethod<[], [string], "view">;

  nextVaultId: TypedContractMethod<[], [bigint], "view">;

  openVault: TypedContractMethod<[], [bigint], "nonpayable">;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeCollateral: TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repay: TypedContractMethod<
    [vaultId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  safetyGuard: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vaults: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { owner: string; active: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCollateral"
  ): TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [vaultId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeVault"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralBalance"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "collateralRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "debtEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHealthFactor"
  ): TypedContractMethod<[vaultId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [[bigint, bigint] & { collateralValue: bigint; debt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "interestRateModel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextVaultId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openVault"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeCollateral"
  ): TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [vaultId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safetyGuard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { owner: string; active: boolean }],
    "view"
  >;

  getEvent(
    key: "Borrowed"
  ): TypedContractEvent<
    BorrowedEvent.InputTuple,
    BorrowedEvent.OutputTuple,
    BorrowedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralAdded"
  ): TypedContractEvent<
    CollateralAddedEvent.InputTuple,
    CollateralAddedEvent.OutputTuple,
    CollateralAddedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralRemoved"
  ): TypedContractEvent<
    CollateralRemovedEvent.InputTuple,
    CollateralRemovedEvent.OutputTuple,
    CollateralRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Repaid"
  ): TypedContractEvent<
    RepaidEvent.InputTuple,
    RepaidEvent.OutputTuple,
    RepaidEvent.OutputObject
  >;
  getEvent(
    key: "VaultClosed"
  ): TypedContractEvent<
    VaultClosedEvent.InputTuple,
    VaultClosedEvent.OutputTuple,
    VaultClosedEvent.OutputObject
  >;
  getEvent(
    key: "VaultOpened"
  ): TypedContractEvent<
    VaultOpenedEvent.InputTuple,
    VaultOpenedEvent.OutputTuple,
    VaultOpenedEvent.OutputObject
  >;

  filters: {
    "Borrowed(uint256,uint256)": TypedContractEvent<
      BorrowedEvent.InputTuple,
      BorrowedEvent.OutputTuple,
      BorrowedEvent.OutputObject
    >;
    Borrowed: TypedContractEvent<
      BorrowedEvent.InputTuple,
      BorrowedEvent.OutputTuple,
      BorrowedEvent.OutputObject
    >;

    "CollateralAdded(uint256,address,uint256,uint256)": TypedContractEvent<
      CollateralAddedEvent.InputTuple,
      CollateralAddedEvent.OutputTuple,
      CollateralAddedEvent.OutputObject
    >;
    CollateralAdded: TypedContractEvent<
      CollateralAddedEvent.InputTuple,
      CollateralAddedEvent.OutputTuple,
      CollateralAddedEvent.OutputObject
    >;

    "CollateralRemoved(uint256,address,uint256,uint256)": TypedContractEvent<
      CollateralRemovedEvent.InputTuple,
      CollateralRemovedEvent.OutputTuple,
      CollateralRemovedEvent.OutputObject
    >;
    CollateralRemoved: TypedContractEvent<
      CollateralRemovedEvent.InputTuple,
      CollateralRemovedEvent.OutputTuple,
      CollateralRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Repaid(uint256,uint256)": TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;
    Repaid: TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;

    "VaultClosed(uint256)": TypedContractEvent<
      VaultClosedEvent.InputTuple,
      VaultClosedEvent.OutputTuple,
      VaultClosedEvent.OutputObject
    >;
    VaultClosed: TypedContractEvent<
      VaultClosedEvent.InputTuple,
      VaultClosedEvent.OutputTuple,
      VaultClosedEvent.OutputObject
    >;

    "VaultOpened(uint256,address)": TypedContractEvent<
      VaultOpenedEvent.InputTuple,
      VaultOpenedEvent.OutputTuple,
      VaultOpenedEvent.OutputObject
    >;
    VaultOpened: TypedContractEvent<
      VaultOpenedEvent.InputTuple,
      VaultOpenedEvent.OutputTuple,
      VaultOpenedEvent.OutputObject
    >;
  };
}
