/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracleRouterSol from "./OracleRouter.sol";
export type { oracleRouterSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as legacy from "./legacy";
export type { legacy };
import type * as mocks from "./mocks";
export type { mocks };
export type { AgentRegistry } from "./AgentRegistry";
export type { ArgentaVault } from "./ArgentaVault";
export type { CollateralRegistry } from "./CollateralRegistry";
export type { DebtEngine } from "./DebtEngine";
export type { ETHUSDOracle } from "./ETHUSDOracle";
export type { InterestRateModel } from "./InterestRateModel";
export type { LSTPriceOracle } from "./LSTPriceOracle";
export type { LiquidationModule } from "./LiquidationModule";
export type { ReputationRegistry } from "./ReputationRegistry";
export type { RoleManager } from "./RoleManager";
export type { SafetyGuard } from "./SafetyGuard";
export type { Stablecoin } from "./Stablecoin";
export type { ValidationRegistry } from "./ValidationRegistry";
