/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SafetyGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAddCollateral"
      | "checkBorrow"
      | "maxCollateralPerVault"
      | "maxDebtPerVault"
      | "maxTotalDebt"
      | "owner"
      | "renounceOwnership"
      | "setLimits"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LimitsUpdated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkAddCollateral",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBorrow",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxCollateralPerVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDebtPerVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTotalDebt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLimits",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAddCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxCollateralPerVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDebtPerVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLimits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LimitsUpdatedEvent {
  export type InputTuple = [
    maxTotalDebt: BigNumberish,
    maxDebtPerVault: BigNumberish,
    maxCollateralPerVault: BigNumberish
  ];
  export type OutputTuple = [
    maxTotalDebt: bigint,
    maxDebtPerVault: bigint,
    maxCollateralPerVault: bigint
  ];
  export interface OutputObject {
    maxTotalDebt: bigint;
    maxDebtPerVault: bigint;
    maxCollateralPerVault: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SafetyGuard extends BaseContract {
  connect(runner?: ContractRunner | null): SafetyGuard;
  waitForDeployment(): Promise<this>;

  interface: SafetyGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAddCollateral: TypedContractMethod<
    [currentCollateralValue: BigNumberish, addValue: BigNumberish],
    [boolean],
    "view"
  >;

  checkBorrow: TypedContractMethod<
    [
      currentVaultDebt: BigNumberish,
      addDebt: BigNumberish,
      totalSystemDebt: BigNumberish
    ],
    [boolean],
    "view"
  >;

  maxCollateralPerVault: TypedContractMethod<[], [bigint], "view">;

  maxDebtPerVault: TypedContractMethod<[], [bigint], "view">;

  maxTotalDebt: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setLimits: TypedContractMethod<
    [
      _maxTotalDebt: BigNumberish,
      _maxDebtPerVault: BigNumberish,
      _maxCollateralPerVault: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAddCollateral"
  ): TypedContractMethod<
    [currentCollateralValue: BigNumberish, addValue: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkBorrow"
  ): TypedContractMethod<
    [
      currentVaultDebt: BigNumberish,
      addDebt: BigNumberish,
      totalSystemDebt: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxCollateralPerVault"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxDebtPerVault"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTotalDebt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLimits"
  ): TypedContractMethod<
    [
      _maxTotalDebt: BigNumberish,
      _maxDebtPerVault: BigNumberish,
      _maxCollateralPerVault: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LimitsUpdated"
  ): TypedContractEvent<
    LimitsUpdatedEvent.InputTuple,
    LimitsUpdatedEvent.OutputTuple,
    LimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "LimitsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      LimitsUpdatedEvent.InputTuple,
      LimitsUpdatedEvent.OutputTuple,
      LimitsUpdatedEvent.OutputObject
    >;
    LimitsUpdated: TypedContractEvent<
      LimitsUpdatedEvent.InputTuple,
      LimitsUpdatedEvent.OutputTuple,
      LimitsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
