/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ICollateralRegistry {
  export type CollateralDataStruct = {
    mcr: BigNumberish;
    liquidationThreshold: BigNumberish;
    maxCap: BigNumberish;
    enabled: boolean;
  };

  export type CollateralDataStructOutput = [
    mcr: bigint,
    liquidationThreshold: bigint,
    maxCap: bigint,
    enabled: boolean
  ] & {
    mcr: bigint;
    liquidationThreshold: bigint;
    maxCap: bigint;
    enabled: boolean;
  };
}

export interface ICollateralRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getParams" | "isSupported"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getParams",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupported",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getParams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSupported",
    data: BytesLike
  ): Result;
}

export interface ICollateralRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ICollateralRegistry;
  waitForDeployment(): Promise<this>;

  interface: ICollateralRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getParams: TypedContractMethod<
    [token: AddressLike],
    [ICollateralRegistry.CollateralDataStructOutput],
    "view"
  >;

  isSupported: TypedContractMethod<[token: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getParams"
  ): TypedContractMethod<
    [token: AddressLike],
    [ICollateralRegistry.CollateralDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSupported"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;

  filters: {};
}
