/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgentRegistry } from "./IAgentRegistry";
export type { IArgentaVault } from "./IArgentaVault";
export type { ICollateralRegistry } from "./ICollateralRegistry";
export type { IDebtEngine } from "./IDebtEngine";
export type { IInterestRateModel } from "./IInterestRateModel";
export type { ILiquidationModule } from "./ILiquidationModule";
export type { IOracleRouter } from "./IOracleRouter";
export type { IReputationRegistry } from "./IReputationRegistry";
export type { ISafetyGuard } from "./ISafetyGuard";
export type { ISessionManager } from "./ISessionManager";
export type { IStablecoin } from "./IStablecoin";
export type { IValidationRegistry } from "./IValidationRegistry";
export type { IWETH } from "./IWETH";
