/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISafetyGuardInterface extends Interface {
  getFunction(
    nameOrSignature: "checkAddCollateral" | "checkBorrow"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkAddCollateral",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBorrow",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAddCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBorrow",
    data: BytesLike
  ): Result;
}

export interface ISafetyGuard extends BaseContract {
  connect(runner?: ContractRunner | null): ISafetyGuard;
  waitForDeployment(): Promise<this>;

  interface: ISafetyGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAddCollateral: TypedContractMethod<
    [currentCollateralValue: BigNumberish, addValue: BigNumberish],
    [boolean],
    "view"
  >;

  checkBorrow: TypedContractMethod<
    [
      currentVaultDebt: BigNumberish,
      addDebt: BigNumberish,
      totalSystemDebt: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAddCollateral"
  ): TypedContractMethod<
    [currentCollateralValue: BigNumberish, addValue: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkBorrow"
  ): TypedContractMethod<
    [
      currentVaultDebt: BigNumberish,
      addDebt: BigNumberish,
      totalSystemDebt: BigNumberish
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
