/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IValidationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getValidation" | "submitValidation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ValidationSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "getValidation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitValidation",
    values: [AddressLike, BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitValidation",
    data: BytesLike
  ): Result;
}

export namespace ValidationSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    agent: AddressLike,
    jobHash: BytesLike,
    valid: boolean,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    agent: string,
    jobHash: string,
    valid: boolean,
    submitter: string
  ];
  export interface OutputObject {
    id: bigint;
    agent: string;
    jobHash: string;
    valid: boolean;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IValidationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IValidationRegistry;
  waitForDeployment(): Promise<this>;

  interface: IValidationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getValidation: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, boolean, string, bigint] & {
        agent: string;
        jobHash: string;
        valid: boolean;
        submitter: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  submitValidation: TypedContractMethod<
    [agent: AddressLike, jobHash: BytesLike, valid: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getValidation"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, boolean, string, bigint] & {
        agent: string;
        jobHash: string;
        valid: boolean;
        submitter: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitValidation"
  ): TypedContractMethod<
    [agent: AddressLike, jobHash: BytesLike, valid: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ValidationSubmitted"
  ): TypedContractEvent<
    ValidationSubmittedEvent.InputTuple,
    ValidationSubmittedEvent.OutputTuple,
    ValidationSubmittedEvent.OutputObject
  >;

  filters: {
    "ValidationSubmitted(uint256,address,bytes32,bool,address)": TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;
    ValidationSubmitted: TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;
  };
}
