/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  InterestRateModel,
  InterestRateModelInterface,
} from "../../contracts/InterestRateModel";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_baseRate",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "baseRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getBorrowRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161016638038061016683398101604081905261002f91610037565b608052610050565b60006020828403121561004957600080fd5b5051919050565b60805160f861006e60003960008181603b0152607c015260f86000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80631f68f20a146037578063a5cdfa9414606f575b600080fd5b605d7f000000000000000000000000000000000000000000000000000000000000000081565b60405190815260200160405180910390f35b605d607a36600460a1565b7f000000000000000000000000000000000000000000000000000000000000000092915050565b6000806040838503121560b357600080fd5b5050803592602090910135915056fea2646970667358221220779ec54a2d4b037abd79906bbce2c09ff3d3abdf51698880b0b29891875d724664736f6c63430008140033";

type InterestRateModelConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InterestRateModelConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InterestRateModel__factory extends ContractFactory {
  constructor(...args: InterestRateModelConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _baseRate: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_baseRate, overrides || {});
  }
  override deploy(
    _baseRate: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_baseRate, overrides || {}) as Promise<
      InterestRateModel & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): InterestRateModel__factory {
    return super.connect(runner) as InterestRateModel__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InterestRateModelInterface {
    return new Interface(_abi) as InterestRateModelInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): InterestRateModel {
    return new Contract(address, _abi, runner) as unknown as InterestRateModel;
  }
}
