/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICollateralRegistry,
  ICollateralRegistryInterface,
} from "../../../contracts/interfaces/ICollateralRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getParams",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "mcr",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxCap",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "enabled",
            type: "bool",
          },
        ],
        internalType: "struct ICollateralRegistry.CollateralData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "isSupported",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICollateralRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ICollateralRegistryInterface {
    return new Interface(_abi) as ICollateralRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICollateralRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICollateralRegistry;
  }
}
