/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILiquidationModule,
  ILiquidationModuleInterface,
} from "../../../contracts/interfaces/ILiquidationModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
    ],
    name: "getHealthFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
    ],
    name: "liquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILiquidationModule__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidationModuleInterface {
    return new Interface(_abi) as ILiquidationModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILiquidationModule {
    return new Contract(address, _abi, runner) as unknown as ILiquidationModule;
  }
}
