/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationRegistry,
  IReputationRegistryInterface,
} from "../../../contracts/interfaces/IReputationRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "newScore",
        type: "int256",
      },
    ],
    name: "ScoreUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "scoreOf",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "int256",
        name: "newScore",
        type: "int256",
      },
    ],
    name: "setScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputationRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationRegistryInterface {
    return new Interface(_abi) as IReputationRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IReputationRegistry;
  }
}
