/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISafetyGuard,
  ISafetyGuardInterface,
} from "../../../contracts/interfaces/ISafetyGuard";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "currentCollateralValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "addValue",
        type: "uint256",
      },
    ],
    name: "checkAddCollateral",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "currentVaultDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "addDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalSystemDebt",
        type: "uint256",
      },
    ],
    name: "checkBorrow",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISafetyGuard__factory {
  static readonly abi = _abi;
  static createInterface(): ISafetyGuardInterface {
    return new Interface(_abi) as ISafetyGuardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISafetyGuard {
    return new Contract(address, _abi, runner) as unknown as ISafetyGuard;
  }
}
