/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISessionManager,
  ISessionManagerInterface,
} from "../../../contracts/interfaces/ISessionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "allowed",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISessionManager__factory {
  static readonly abi = _abi;
  static createInterface(): ISessionManagerInterface {
    return new Interface(_abi) as ISessionManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISessionManager {
    return new Contract(address, _abi, runner) as unknown as ISessionManager;
  }
}
