/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IValidationRegistry,
  IValidationRegistryInterface,
} from "../../../contracts/interfaces/IValidationRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "jobHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "address",
        name: "submitter",
        type: "address",
      },
    ],
    name: "ValidationSubmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getValidation",
    outputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "jobHash",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
      {
        internalType: "address",
        name: "submitter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "jobHash",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
    ],
    name: "submitValidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IValidationRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IValidationRegistryInterface {
    return new Interface(_abi) as IValidationRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IValidationRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IValidationRegistry;
  }
}
