/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAggregator } from "./MockAggregator";
export type { MockERC20 } from "./MockERC20";
export type { MockTarget } from "./MockTarget";
export type { MockWETH } from "./MockWETH";
